### ISSUE TITLE
 Not able to run db migration to bootstrap the database

### ISSUE THREAD

**Issue by bqbn** [mozilla/buildhub2#203] opened 2018-08-09 20:45 UTC
# Background

Resources for -stage environment (database, elasticsearch, application stack and etc.) are set up and the application is able to start up.

Trying to run the `migrate` command for the first time to bootstrap the database in this environment.

# Issue

Here is the command we ran:

```
$ docker run --rm --net host --env-file /etc/dockerflow/buildhub2.txt --log-driver=syslog hub.prod.mozaws.net/pipelines/buildhub2/buildhub2:latest migrate
```

And here is the error:

```
Not waiting for any services
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from configurations.management import execute_from_command_line
  File "/usr/local/lib/python3.6/site-packages/configurations/management.py", line 3, in <module>
    importer.install(check_options=True)
  File "/usr/local/lib/python3.6/site-packages/configurations/importer.py", line 49, in install
    importer = ConfigurationImporter(check_options=check_options)
  File "/usr/local/lib/python3.6/site-packages/configurations/importer.py", line 67, in __init__
    self.check_options()
  File "/usr/local/lib/python3.6/site-packages/configurations/importer.py", line 87, in check_options
    add_help=False)
TypeError: __init__() takes 1 positional argument but 2 were given
```

Please note that the user scenario is the same as https://github.com/mozilla/buildhub2/issues/187, but the error this time is different.

**Comment by bqbn** [comment] 2018-08-09 20:45
@peterbe fyi

**Comment by peterbe** [comment] 2018-08-09 21:06
Tricky. I don't know what it might be but it's got nothing to do with the `migrate` command in particular. It's just that that's the first thing we've attempted. I can't really ask you for the content of the `/etc/dockerflow/buildhub2.txt` because it probably has a bunch of secrets. 

The error is to do with the conversion from environment variables to Django settings. 
Clearly there's something in this environment (populated from the `--env-file`) that is causing deeper trouble in `django-configurations`. 

Is it an option for you to securely send me your `buildhub2.txt` file but with the juicy bits scrubbed. If you could scrub it I might be able to reproduce the "boot up problem". Obviously, if the values are scrubbed I'd get other errors but we need to get beyond the conversion from env vars to Python.

**Comment by bqbn** [comment] 2018-08-09 21:19
Below is what's in `/etc/dockerflow/buildhub2.txt`:

```
DATABASE_URL=postgres://<db_user>:<db_pass>@<db_hostname>:5432/buildhub2
DJANGO_ALLOWED_HOSTS=buildhub2.stage.mozaws.net
DJANGO_CONFIGURATION=Stage
DJANGO_ES_URLS=http://internal-buildhub2-es-s-ELB-xxxxxxxxxx-1034878185.us-east-1.elb.amazonaws.com:9200
DJANGO_S3_BUCKET_URL=https://s3.amazon.com
DJANGO_SECRET_KEY=a_long_alpha_numeric_string_without_special_characters
DJANGO_SQS_QUEUE_URL=https://sqs.us-east-1.amazonaws.com/xxxxxxxxxxxx/buildhub2-resources-stage-batch1-SQSQueue-xxxxxxxxxxxx
GUNICORN_WORKERS=5
SENTRY_DSN=https://<user>:<pass>@sentry.prod.mozaws.net/386
SENTRY_PUBLIC_DSN=https://<user>@sentry.prod.mozaws.net/386
```

Let me know if anything is missing or wrong.

I should add that the application itself can start up fine with the same `buildhub2.txt` env file.

**Comment by bqbn** [comment] 2018-08-09 21:39
It could be because of this: https://github.com/jazzband/django-configurations/issues/203

**Comment by peterbe** [comment] 2018-08-10 13:06
Good catch! I just downgrade it to https://github.com/mozilla/buildhub2/pull/207 and now I'll try to remember to try the whole thing after django-configurations is released with a fix.

**Comment by peterbe** [comment] 2018-08-10 13:36
Try now.

**Closed** 2018-08-10 13:36 UTC
