### ISSUE TITLE
buildhub2 -stage web site fails to load the second time

### ISSUE THREAD

**Issue by bqbn** [mozilla/buildhub2#245] opened 2018-08-25 00:00 UTC
## STR

The issue can be reproduced in both Firefox and Chrome browser. I describe the steps to reproduce it in Chrome browser first, and in Firefox browser later.

1. open a chrome incognito window (this way it is a clean slate without any local caches).
2. open the `Developer Tools` pannel in the window and click on the `network` tab so you can watch the networking activities.
3. visit `https://buildhub2.stage.mozaws.net`
4. note the website is loaded correctly (even though there are 4 javascript errors in the `console` tab)
5. click the reload button to reload the page.
6. And see that the website is not reloading and shows a "Welcome to nginx" message.

The issue can be re-produced in Firefox browser as well. The only difference is that if using a Firefox browser, between the above step 4 and 5, you need to wait for more than 24 hours (presumably, that is the amount of time specified in the response `cache-control` header, where it demands `max-age=86400, public` for the root page.

## Other notes
1. In the step 5 above, when clicking the reload button,  the following two requests were received at the server end.

    ```
    "GET /favicon.ico HTTP/1.1" 200 34885 ...
    "GET /service-worker.js HTTP/1.1" 200 1383 ...
    ```

2. In both browsers, running the following code in the javascript console will allow the web site to reload again.

    ```
    navigator.serviceWorker.ready.then(registration => { registration.unregister(); });
    ```

**Comment by bqbn** [comment] 2018-08-25 00:00
@peterbe fyi

**Comment by peterbe** [comment] 2018-08-27 15:11
Wow! This is terrible. And I'm curious how it could have happened. Let's ignore the manifestation of the problems with the service worker. The ultimately root cause seems to be that it tries to connect to `http://localhost:8000/api/search` which only ever makes sense when doing local dev. 

We might need to dig into how we generate the static assets for production use.

**Comment by peterbe** [comment] 2018-08-28 16:35
GitHub is being weird and refusing leaving https://github.com/mozilla/buildhub2/pull/253 open and saying it has conflicts. But it's [landed in master](https://github.com/mozilla/buildhub2/commit/bff705d53498719242d68cb96c0263ee6613ae9e).

Please test the latest master now.

**Comment by bqbn** [comment] 2018-08-30 03:59
Deployed the latest master to -stage, and the issue doesn't seem to be resolved.

The same STR applies (using Chrome browser for example).

It looks like the previous `http://localhost:8000/api/search` issue has been fixed. However, there is still a 500 error when the browser client tries to POST to `https://buildhub2.stage.mozaws.net/api/search`. 

The application log showed the following,

```
Aug 30 03:53:36 ip-172-31-35-73.ec2.internal docker-buildhub2[2675]: {"Timestamp": 1535601216544661760, "Type": "django.request", "Logger": "buildhub", "Hostname": "ip-172-31-35-73.ec2.internal", "EnvVersion": "2.0", "Severity": 3, "Pid": 13, "Fields": {"status_code": 500, "request": "<WSGIRequest: POST '/api/search'>", "msg": "Internal Server Error: /api/search", "error": "NotFoundError(404, 'index_not_found_exception', {'error': {'root_cause': [{'type': 'index_not_found_exception', 'reason': 'no such index', 'resource.type': 'index_or_alias', 'resource.id': 'buildhub2', 'index_uuid': '_na_', 'index': 'buildhub2'}], 'type': 'index_not_found_exception', 'reason': 'no such index', 'resource.type': 'index_or_alias', 'resource.id': 'buildhub2', 'index_uuid': '_na_', 'index': 'buildhub2'}, 'status': 404})", "traceback": "Uncaught exception:\n  File \"/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py\", line 35, in inner\n    response = get_response(request)\n  File \"/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py\", line 128, in _get_response\n    response = self.process_exception_by_middleware(e, request)\n  File \"/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py\", line 126, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"/usr/local/lib/python3.6/site-packages/markus/main.py\", line 364, in _timer_decorator\n    return fun(*args, **kwargs)\n  File \"/app/buildhub/api/views.py\", line 28, in search\n    response = search.execute()\n  File \"/usr/local/lib/python3.6/site-packages/elasticsearch_dsl/search.py\", line 679, in execute\n    **self._params\n  File \"/usr/local/lib/python3.6/site-packages/elasticsearch/client/utils.py\", line 76, in _wrapped\n    return func(*args, params=params, **kwargs)\n  File \"/usr/local/lib/python3.6/site-packages/elasticsearch/client/__init__.py\", line 655, in search\n    doc_type, '_search'), params=params, body=body)\n  File \"/usr/local/lib/python3.6/site-packages/elasticsearch/transport.py\", line 318, in perform_request\n    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)\n  File \"/usr/local/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py\", line 185, in perform_request\n    self._raise_error(response.status, raw_data)\n  File \"/usr/local/lib/python3.6/site-packages/elasticsearch/connection/base.py\", line 125, in _raise_error\n    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)\n<class 'elasticsearch.exceptions.NotFoundError'>\nNotFoundError(404, 'index_not_found_exception', {'error': {'root_cause': [{'type': 'index_not_found_exception', 'reason': 'no such index', 'resource.type': 'index_or_alias', 'resource.id': 'buildhub2', 'index_uuid': '_na_', 'index': 'buildhub2'}], 'type': 'index_not_found_exception', 'reason': 'no such index', 'resource.type': 'index_or_alias', 'resource.id': 'buildhub2', 'index_uuid': '_na_', 'index': 'buildhub2'}, 'status': 404})\n"}}
Aug 30 03:53:36 ip-172-31-35-73.ec2.internal docker-buildhub2[2675]: 127.0.0.1 - - [30/Aug/2018:03:53:36 +0000] "POST /api/search HTTP/1.0" 500 27 "https://buildhub2.stage.mozaws.net/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36"
```

**Comment by peterbe** [comment] 2018-08-30 13:37
The error is that the Elasticsearch index hasn't been created yet:
```
{
  "status": 404,
  "error": {
    "index_uuid": "_na_",
    "index": "buildhub2",
    "resource.type": "index_or_alias",
    "root_cause": [
      {
        "index_uuid": "_na_",
        "index": "buildhub2",
        "resource.type": "index_or_alias",
        "resource.id": "buildhub2",
        "reason": "no such index",
        "type": "index_not_found_exception"
      }
    ],
    "reason": "no such index",
    "type": "index_not_found_exception",
    "resource.id": "buildhub2"
  }
}
```

I have to refresh my memory as to how you bootstrap when you start from scratch.

**Comment by peterbe** [comment] 2018-08-31 16:36
Redirecting to https://github.com/mozilla/buildhub2/issues/263 instead. 
The problem is that it's not documented how to start from scratch.

**Comment by bqbn** [comment] 2018-09-06 00:44
So we re-deployed the latest version of the app, followed the latest documentation and created the Elasticsearch index, by running `./manage.py reindex-elasticsearch`.

Now the 500 used to be seen in the console is gone. However, the same issue (that the web site fails to load the second time) still exists and the same STR still applies.

**Comment by peterbe** [comment] 2018-09-06 14:04
Hmm.. It clearly still is busted. I'm going to try to replicate this locally.

**Comment by peterbe** [comment] 2018-09-06 14:49
I can't reproduce this locally. I have https locally so as to simulate service workers on my laptop. 
My scripting starts a uwsgi server on `:8000` and I don't run the Node dev server. So all requests are routed through Whitenoise. In my local Nginx I use:

```
    location / {
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Host "";
        proxy_set_header Host $http_host;
        proxy_pass http://127.0.0.1:8000;
    }
```
...*only*. So there's no serving of static files directly between Nginx and the client. Everything goes through Whitenoise and the generated build files. 

Also, when I ran the latest `yarn run build` it generated...:

```
▶ ls -R ui/build/static
css js

ui/build/static/css:
main.8741ee2b.css     main.8741ee2b.css.map

ui/build/static/js:
main.a608c2ef.js     main.a608c2ef.js.map
```

We should check that those are the same files that get served in Stage.

**Comment by bqbn** [comment] 2018-09-11 01:03
As discussed in #storage channel, the cause of this issue is that the `service-workers.js`, which is loaded into the browser tries to download a list of URLs from the site, and one of which is `/index.html`. The default behavior of Nginx is to serve that file from local disk and that's what causes the issue (seeing the "Welcome to nginx" message upon clicking the reload button).

We changed the Nginx so that every URL unless explicitly excluded is sent to the app container directly, and that seems to have solved the problem.

**Comment by peterbe** [comment] 2018-09-11 12:58
By the way, I researched it bit. The reason why our service-worker.js has to use `/index.html` instead of `/` is complicated. I don't remember the exact reasons but it's unlikely to change or be fixed. We just need to remember to "always" make it a valid alias. Our Whitenoise configuration does that. Our mistake was to allow static files from Nginx from the wrong container.

**Comment by peterbe** [comment] 2018-11-06 19:55
This still happens! :(
It's impossible to reproduce browsers that haven't visited https://buildhub2.stage.mozaws.net/ before so it's most likely a rogue service worker somewhere.

**Comment by peterbe** [comment] 2018-11-21 13:50
Solved with shipping a new service worker.

**Closed by peterbe** 2018-11-21 13:50 UTC
